import "../../../globals.css";
import NavServer from "./nav/nav-server";
import Footer from "../(model)/[model]/components/ui/panel/components/footer";
import AuthBanner from "../(model)/[model]/components/ui/panel/components/auth-banner";
import { ThemeProvider } from "../../../theme-provider"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      // data-mode="light"
      lang="en">
      <body
        className="relative dark:bg-black dark:text-white bg-white text-black transition-colors duration-300 ease-in antialiased"
      >
        <ThemeProvider>

          <NavServer />
          {children}
          <AuthBanner
            key={'search'}
          />
          <Footer />
        </ThemeProvider>
       
      </body>
    </html>
  );
}
